# Generated by Django 6.0.7 on 2026-07-17 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Donor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donor_id', models.CharField(db_index=True, max_length=50, unique=True)),
                ('name', models.CharField(db_index=True, max_length=150)),
                ('age', models.PositiveBigIntegerField()),
                ('gender', models.CharField(db_index=True, max_length=20)),
                ('blood_group', models.CharField(db_index=True, max_length=10)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.TextField(blank=True)),
                ('city', models.CharField(db_index=True, max_length=100)),
                ('state', models.CharField(db_index=True, max_length=100)),
                ('country', models.CharField(db_index=True, default='India', max_length=100)),
                ('medical_history', models.TextField(blank=True)),
                ('last_donation_date', models.DateField(blank=True, null=True)),
                ('eligible_date', models.DateField(blank=True, db_index=True, null=True)),
                ('donation_count', models.PositiveIntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('hospital', models.CharField(blank=True, max_length=200)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
